# Generated by Django 2.2.3 on 2021-04-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture_head',
            field=models.ImageField(default='blog/img/blog/inner_b1b.webp', upload_to='img/blog'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
