# Generated by Django 2.2.3 on 2021-04-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210425_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture_head',
            new_name='head_img',
        ),
    ]
