# Generated by Django 2.2.3 on 2021-04-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210425_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='head_img',
        ),
        migrations.AddField(
            model_name='post',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='post/%Y%m%d/'),
        ),
    ]
