# Generated by Django 2.2.3 on 2021-04-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210425_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='post/%Y%m/'),
        ),
    ]
