# Generated by Django 2.2.3 on 2021-04-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210426_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='elapsed_time',
            field=models.IntegerField(blank=True, default=5, verbose_name='阅读时长'),
        ),
        migrations.AlterField(
            model_name='post',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='post/%Y%m/', verbose_name='标题图'),
        ),
    ]
